const Menu = [
  {
    name: "Classic Pancakes",
    type: "Breakfast",
    price: 7.99,
    ingredients: ["Flour", "Milk", "Eggs", "Butter", "Maple Syrup"],
    vegetarian: true,
    img: "https://cdn.loveandlemons.com/wp-content/uploads/2022/09/oatmeal-pancakes.jpg",
  },
  {
    name: "Eggs Benedict",
    type: "Breakfast",
    price: 9.99,
    ingredients: [
      "English Muffin",
      "Poached Eggs",
      "Canadian Bacon",
      "Hollandaise Sauce",
    ],
    vegetarian: false,
    img: "https://www.allrecipes.com/thmb/QVMaPhXnj1HQ70C7Ka9WYtuipHg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/17205-eggs-benedict-DDMFS-4x3-a0042d5ae1da485fac3f468654187db0.jpg",
  },
  {
    name: "Greek Yogurt Parfait",
    type: "Breakfast",
    price: 6.99,
    ingredients: ["Greek Yogurt", "Granola", "Berries", "Honey"],
    vegetarian: true,
    img: "https://getinspiredeveryday.com/wp-content/uploads/2022/04/Fruit-and-Yogurt-Parfaits-Get-Inspired-Everyday-12.jpg",
  },
  {
    name: "Avocado Toast",
    type: "Breakfast",
    price: 8.99,
    ingredients: ["Sourdough Bread", "Avocado", "Tomato Slices", "Eggs"],
    vegetarian: true,
    img: "https://www.eatingwell.com/thmb/CTSAuY2CRbo0Ivw4wbfIydhy7Qw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1807w-avocado-toast-recipe-8029771-2000-aefaa92c11e74e80b0bfc15788a61465.jpg",
  },
  {
    name: "Belgian Waffles",
    type: "Breakfast",
    price: 10.99,
    ingredients: [
      "Waffle Batter",
      "Whipped Cream",
      "Fresh Berries",
      "Powdered Sugar",
    ],
    vegetarian: true,
    img: "https://stordfkenticomedia.blob.core.windows.net/df-us/rms/media/recipemediafiles/recipes/retail/x17/2020_belgian-style-waffles_16700_600x600.jpg?ext=.jpg",
  },
  {
    name: "Omelette",
    type: "Breakfast",
    price: 11.99,
    ingredients: ["Eggs", "Cheese", "Bell Peppers", "Onions", "Ham"],
    vegetarian: false,
    img: "https://joyfoodsunshine.com/wp-content/uploads/2022/07/best-omelette-recipe-1.jpg",
  },
  {
    name: "French Toast",
    type: "Breakfast",
    price: 8.99,
    ingredients: ["Bread", "Eggs", "Milk", "Cinnamon", "Powdered Sugar"],
    vegetarian: true,
    img: "https://joyfoodsunshine.com/wp-content/uploads/2018/05/best-easy-french-toast-recipe-4.jpg",
  },
  {
    name: "Breakfast Burrito",
    type: "Breakfast",
    price: 9.99,
    ingredients: [
      "Scrambled Eggs",
      "Black Beans",
      "Cheese",
      "Salsa",
      "Tortilla",
    ],
    vegetarian: true,
    img: "https://plantbasedonabudget.com/wp-content/uploads/2013/04/Vegan-Easy-Breakfast-Burritos-Plant-Based-on-a-Budget-1-2.jpg"
  },
  {
    name: "Smoked Salmon Bagel",
    type: "Breakfast",
    price: 12.99,
    ingredients: [
      "Bagel",
      "Cream Cheese",
      "Smoked Salmon",
      "Red Onion",
      "Capers",
    ],
    vegetarian: false,
    img: "https://www.dontgobaconmyheart.co.uk/wp-content/uploads/2020/04/salmon-cream-cheese-bagel.jpg",
  },
  {
    name: "Fruit Smoothie Bowl",
    type: "Breakfast",
    price: 7.99,
    ingredients: [
      "Mixed Berries",
      "Banana",
      "Greek Yogurt",
      "Granola",
      "Honey",
    ],
    vegetarian: true,
    img: "https://www.twopeasandtheirpod.com/wp-content/uploads/2023/06/Acai-Bowl-10.jpg",
  },
  {
    name: "Chicken Caesar Salad",
    type: "Lunch",
    price: 10.99,
    ingredients: [
      "Grilled Chicken",
      "Romaine Lettuce",
      "Croutons",
      "Parmesan Cheese",
      "Caesar Dressing",
    ],
    vegetarian: false,
    img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Low-carb-Caesar-salad-4.jpg",
  },
  {
    name: "Turkey Club Sandwich",
    type: "Lunch",
    price: 11.99,
    ingredients: [
      "Turkey",
      "Bacon",
      "Lettuce",
      "Tomato",
      "Mayonnaise",
      "Whole Wheat Bread",
    ],
    vegetarian: false,
    img: "https://dinnersdishesanddesserts.com/wp-content/uploads/2022/03/Turkey-Club-Sandwich-square-scaled-735x735.jpg",
  },
  {
    name: "Vegetarian Wrap",
    type: "Lunch",
    price: 9.99,
    ingredients: ["Hummus", "Avocado", "Lettuce", "Tomato", "Whole Wheat Wrap"],
    vegetarian: true,
    img: "https://hurrythefoodup.com/wp-content/uploads/2022/11/20-Vegetarian-Wraps-Super-Tasty-title-Image.jpg",
  },
  {
    name: "Caprese Pasta Salad",
    type: "Lunch",
    price: 8.99,
    ingredients: [
      "Pasta",
      "Cherry Tomatoes",
      "Mozzarella Cheese",
      "Basil",
      "Balsamic Vinaigrette",
    ],
    vegetarian: true,
    img: "https://www.twopeasandtheirpod.com/wp-content/uploads/2020/06/Caprese-Pasta-Salad-3.jpg",
  },
  {
    name: "Grilled Cheese Panini",
    type: "Lunch",
    price: 7.99,
    ingredients: [
      "Cheddar Cheese",
      "Swiss Cheese",
      "Tomato",
      "Sourdough Bread",
    ],
    vegetarian: true,
    img: "https://healthyhappylife.com/wp-content/uploads/2012/05/daiya-large-cheese-sandwich564_edited-3.jpg",
  },
  {
    name: "Beef Burrito Bowl",
    type: "Lunch",
    price: 12.99,
    ingredients: ["Seasoned Beef", "Black Beans", "Rice", "Salsa", "Guacamole"],
    vegetarian: false,
    img: "https://kjsfoodjournal.com/wp-content/uploads/2022/08/img_4393-scaled-e1660820401657-500x500.jpg",
  },
  {
    name: "Mushroom and Spinach Quesadilla",
    type: "Lunch",
    price: 10.99,
    ingredients: ["Mushrooms", "Spinach", "Cheese", "Flour Tortilla"],
    vegetarian: true,
    img: "https://www.budgetbytes.com/wp-content/uploads/2022/02/Spinach-and-Mushroom-Quesadillas-stack.jpg",
  },
  {
    name: "Lemon Herb Grilled Salmon",
    type: "Lunch",
    price: 14.99,
    ingredients: ["Salmon", "Lemon", "Garlic", "Herbs", "Quinoa"],
    vegetarian: false,
    img: "https://www.cuisinart.com/globalassets/recipes/recipe_9918_676836842.jpg",
  },
  {
    name: "Chicken Pesto Pasta",
    type: "Lunch",
    price: 13.99,
    ingredients: [
      "Grilled Chicken",
      "Pesto Sauce",
      "Cherry Tomatoes",
      "Parmesan Cheese",
    ],
    vegetarian: false,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG4JbwuGYfZTNb-lPsEFd0_1_yFCA15WopzA&usqp=CAU",
  },
  {
    name: "Chickpea and Couscous Salad",
    type: "Lunch",
    price: 9.99,
    ingredients: [
      "Chickpeas",
      "Couscous",
      "Cucumber",
      "Red Onion",
      "Lemon Vinaigrette",
    ],
    vegetarian: true,
    img: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2019-07-recipe-israeli-couscous-salad-feta-chickpeas-herbs%2FIsraeli-Couscous-Salad-Feta-Chickpeas-Herbs_008",
  },
  {
    name: "Grilled Salmon with Lemon Dill Sauce",
    type: "Dinner",
    price: 16.99,
    ingredients: ["Salmon", "Lemon", "Dill", "Olive Oil", "Asparagus"],
    vegetarian: false,
    img: "https://ketocookingchristian.com/wp-content/uploads/2021/07/Baked-Salmon-with-Creamy-Dill-Sauce3-2-scaled.jpeg"
  },
  {
    name: "Beef Tenderloin Steak",
    type: "Dinner",
    price: 19.99,
    ingredients: [
      "Beef Tenderloin",
      "Rosemary",
      "Garlic Butter",
      "Mashed Potatoes",
      "Green Beans",
    ],
    vegetarian: false,
    img: "https://s23209.pcdn.co/wp-content/uploads/2020/12/Garlic-Rosemary-Beef-TenderloinIMG_1412.jpg"
  },
  {
    name: "Vegetable Stir-Fry with Tofu",
    type: "Dinner",
    price: 14.99,
    ingredients: ["Tofu", "Broccoli", "Carrots", "Snap Peas", "Soy Sauce"],
    vegetarian: true,
    img: "https://www.skinnytaste.com/wp-content/uploads/2021/09/Tofu-Stir-Fry-8.jpg"
  },
  {
    name: "Chicken Marsala",
    type: "Dinner",
    price: 15.99,
    ingredients: ["Chicken Breast", "Marsala Wine Sauce", "Mushrooms", "Pasta"],
    vegetarian: false,
    img: "https://bellyfull.net/wp-content/uploads/2023/08/Chicken-Marsala-blog-1.jpg"
  },
  {
    name: "Eggplant Parmesan",
    type: "Dinner",
    price: 13.99,
    ingredients: [
      "Eggplant",
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Parmesan Cheese",
      "Spaghetti",
    ],
    vegetarian: true,
    img: "https://www.allrecipes.com/thmb/L9wpL6T8bgfo7C09-Euoa-OSN0A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25321-eggplant-parmesan-ii-DDMFS-4x3-6d53ce79765b4c3d9f554d2a47e14d00.jpg"
  },
  {
    name: "Shrimp Scampi Linguine",
    type: "Dinner",
    price: 17.99,
    ingredients: ["Shrimp", "Garlic", "White Wine Sauce", "Linguine Pasta"],
    vegetarian: false,
    img: "https://www.allrecipes.com/thmb/jiV_4f8vXFle1RdFLgd8-_31J3M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/229960-shrimp-scampi-with-pasta-DDMFS-4x3-e065ddef4e6d44479d37b4523808cc23.jpg"
  },
  {
    name: "Butternut Squash Risotto",
    type: "Dinner",
    price: 15.99,
    ingredients: [
      "Butternut Squash",
      "Arborio Rice",
      "Parmesan Cheese",
      "Vegetable Broth",
    ],
    vegetarian: true,
    img: "https://cdn.loveandlemons.com/wp-content/uploads/2021/10/butternut-squash-risotto-1.jpg"
  }, 
  {
    name: "Lemon Herb Grilled Chicken",
    type: "Dinner",
    price: 16.99,
    ingredients: [
      "Chicken Breast",
      "Lemon",
      "Herbs",
      "Quinoa",
      "Roasted Vegetables",
    ],
    vegetarian: false,
    img: "https://feelgoodfoodie.net/wp-content/uploads/2019/07/Grilled-Lemon-Chicken-4.jpg"
  },
  {
    name: "Pork Chops with Apple Compote",
    type: "Dinner",
    price: 18.99,
    ingredients: [
      "Pork Chops",
      "Apples",
      "Cinnamon",
      "Brown Sugar",
      "Mashed Sweet Potatoes",
    ],
    vegetarian: false,
    img: "https://mariosmeatmarket.com/wp-content/uploads/2018/12/Marios-Italian-Deli-Pork-Chops-with-Apple-Compote.jpg"
  },
  {
    name: "Vegetarian Enchiladas",
    type: "Dinner",
    price: 14.99,
    ingredients: ["Black Beans", "Cheese", "Enchilada Sauce", "Tortillas"],
    vegetarian: true,
    img: "https://pinchofyum.com/wp-content/uploads/Vegetarian-Enchiladas-on-Plate.jpg"
  },
 
];
export { Menu };
